### ISSUE TITLE
Algorand Indexer Large Block Handling

### ISSUE THREAD

**Issue by winder** [subquery/subql-algorand#18]
Hello, I'm an Algorand developer working on our Indexer service. It was a nice surprise to see that you've included Algorand with your product! I was curious how you're fetching data and noticed a potential problem.

### Description

The getTxns / getBlockByHeight functions may fail for blocks with many transactions (by default, blocks with >10k transactions). Our testnet deployment contains some blocks like this. [Here is one example](https://testnet.algoexplorer.io/block/24148752).

You are using the lookupBlock (`/v2/blocks/{block}`) endpoint, which currently returns all transactions for that particular block. We recently made a change to this endpoint which limits this endpoint which limits the number of transactions for a block according to the `--max-transactions-limit` setting.
```
export async function getBlockByHeight(
  api: Indexer,
  height: number,
): Promise<AlgorandBlock> {
  try {
    const blockInfo = await api.lookupBlock(height).do();
    return camelCaseObjectKey(blockInfo);
  } catch (error) {
    logger.error(`failed to fetch Block at round ${height}`);
    throw error;
  }
}
```

# Solutions

Two options:
1) ensure that you set `--max-transactions-limit` to a large number. Today 27,000 would work but this may be changed in the future.
2) use `/v2/blocks/{round}&header-only=true` and `/v2/transactions?round={round}` with result pagination.

**Comment by stwiname** [comment]
@winder thanks for your feedback. We'll make these improvement when we can find some time.
